version: '3'

services: 
  db:
    image: 'mysql:5.7'
    command: --innodb-use-native-aio=0
    container_name: 'app_mysql'
    security_opt:
      - apparmor=unconfined
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=group_events
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

